### ISSUE TITLE
get-bc not working

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/gllvm#1]
OK  I have to do some other things, but I can't get `get-bc` to work on my mac.

It took me a while to get `gclang` to work, see f42fbca27377507e0727bdd272d2027a54f1698e

but now I canna get the bitcode.  To reproduce:

```
cd whole-program-llvm/test/test_files

CC=gclang make many

get-bc main
```
The problem seems to be that `filesToLink` is `[]` @loicgelle

**Comment by loicgelle** [comment]
@ianamason Is the problem specific to binaries?

**Comment by ianamason** [comment]
not sure. i'm testing it now on linux. took a while to get my vagrant box up and coughing.
will look into it momentarily.

**Comment by ianamason** [comment]
No seems to not work pretty uniformly.  try some of the simple examples in 
`whole-program-llvm/test/test_files`

```
CC=gclang make archive
get-bc libfoo.a
```

```
CC=gclang make many

get-bc main
```


etc

**Comment by loicgelle** [comment]
@ianamason Working on that issue. Bitcode from libraries + objects are extracted fine on Mac, the problem must lie in the method for reading/writing .llvm_bc sections to objects and libraries.

As for binaries, I am not surprised. Look here at line 81: https://github.com/SRI-CSL/whole-program-llvm/blob/master/wllvm/compilers.py

**Comment by ianamason** [comment]
OK I will let you fix the issue.  Yes executable binaries get their section from the linker.
But they still contain sections.

**Comment by loicgelle** [comment]
@ianamason No problem for me to build/extract objects/libraries in a Linux Docker machine. Probably you did not install llvm tools (like llvm-ar / llvm-link) in your Vagrant box

**Comment by loicgelle** [comment]
@ianamason My bad, I had to change something in the way the output filename is generated. Checkout the latest commit.

**Comment by ianamason** [comment]
Nope still doesn't work.
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/whole-program-llvm/test/test_files$ CC=gclang make many
gclang foo.c -c
gclang bar.c -c
gclang baz.c -c
gclang main.c -c
gclang foo.o bar.o baz.o main.o -o main
vagrant@vagrant-ubuntu-trusty-64:/vagrant/whole-program-llvm/test/test_files$ get-bc main
2017/06/28 16:58:52 There was an error reading the contents of main. Make sure that the 'objcopy' command is installed.
vagrant@vagrant-ubuntu-trusty-64:/vagrant/whole-program-llvm/test/test_files$ ls -la main.bc
ls: cannot access main.bc: No such file or directory
vagrant@vagrant-ubuntu-trusty-64:/vagrant/whole-program-llvm/test/test_files$ extract-bc main
vagrant@vagrant-ubuntu-trusty-64:/vagrant/whole-program-llvm/test/test_files$ ls -la main.bc
-rw-r--r-- 1 vagrant vagrant 1788 Jun 28 16:59 main.bc
vagrant@vagrant-ubuntu-trusty-64:/vagrant/whole-program-llvm/test/test_files$
```

**Comment by loicgelle** [comment]
@ianamason I was saying that I fixed objects and libraries, not binaries. I've just fixed binaries for *nix only and pushed, you can test.

For Mac still not working for some strange reason. Even though I doubt it is related to that, I will try to clean the mess of the extractSectionDarwin function.

**Comment by ianamason** [comment]
OK gotcha. Still getting the same behaviour, though :-(

**Comment by loicgelle** [comment]
@ianamason My version of objcopy is 2.28. Can you run `objcopy --dump-section .llvm_bc=/dev/stdout main` and give me the output? Mine is:
```
/root/go/src/gllvm/.foo.o.bc
/root/go/src/gllvm/.bar.o.bc
/root/go/src/gllvm/.baz.o.bc
/root/go/src/gllvm/.main.o.bc
```

**Comment by ianamason** [comment]
Yes that is what I was doing. My version is 2.24 and it hasn't got that feature :-(
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/whole-program-llvm/test/test_files$ objcopy --dump-section .llvm_bc=/dev/stdout main
objcopy: unrecognized option '--dump-section'
```

**Comment by loicgelle** [comment]
@ianamason We have to make a choice then. Either we revert back to legacy support, which probably means a messy extracting function like the one for Darwin, or we precise the need for a working version of objcopy.

**Comment by ianamason** [comment]
I think reverting is better. 14.04 is a pretty popular OS.

**Comment by loicgelle** [comment]
Why do we have to deal with legacy dinosaurs... Fine then.

Can you try get-bc for Mac? It's working for me in fact

**Comment by ianamason** [comment]
Yes it seems to work on my mac now.

**Comment by loicgelle** [comment]
@ianamason Fixed.

**Comment by ianamason** [comment]
Yep looks good here too.

**Comment by loicgelle** [comment]
👍
