### ISSUE TITLE
tagged releases?

### ISSUE THREAD

**Issue by dtzWill** [SRI-CSL/gllvm#16]
Helpful for downstream users and packagers to at least know:
* What commit (source tarball) corresponds to version X
* What is suitable for general use vs. the current development work.

Not a big deal, but thought I'd mention it in case it was just an oversight instead of intentional.

Thanks!

**Comment by ianamason** [comment]
Thanks, no it is an oversight (actually just a newbie mistake). I should have a new release in the next 
few days, so I will see if I can get it right. Any checklist anywhere a newbie can follow?

**Comment by ianamason** [comment]
[Thar](https://github.com/SRI-CSL/gllvm/releases/tag/v1.2.0) she blows. Hope she doesn't blow too hard.  Compiles the Linux kernel.
