### ISSUE TITLE
Link error with asan

### ISSUE THREAD

**Issue by HongxuChen** [SRI-CSL/gllvm#19]
When I compile with Address Sanitizer, gclang/gclang++ fails to link.

```c
// test.c
#include <stdio.h>
int main(void) {
    printf("test\n");
}
```

```bash
$ gclang test.c -fsanitize=address 
.test.o: In function `asan.module_ctor':
test.c:(.text+0x32): undefined reference to `__asan_init'
test.c:(.text+0x37): undefined reference to `__asan_version_mismatch_check_v8'
test.c:(.text+0x4d): undefined reference to `__asan_register_globals'
.test.o: In function `asan.module_dtor':
test.c:(.text+0x73): undefined reference to `__asan_unregister_globals'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR:clang [.test.o -o a.out] failed to link: exit status 1.
```

It compiles fine with `clang test.c -fsanitize=address`.

```bash
$ gclang --version
clang version 6.0.0-svn326550-1~exp1~20180404173946.64 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by ianamason** [comment]
Thanks @HongxuChen! 

I added an explicit compile-link flag for the `-fsanitize=...` case. That way it gets included in both the compile and link phase.  The problem you were seeing was caused by it not being passed to the link step.

My guess is that there are more of these, since our classification of command line arguments is pretty ad hoc.

**Comment by HongxuChen** [comment]
@ianamason Thanks for the fix! Maybe wllvm should apply a similar patch. It seems that this case is special since the option is used both by the compiler and the linker.
BTW, may I know a detailed description of advantages of gllvm/wllvm over gold linker? I actually knew wllvm firstly, however I recognized that gold linker can generate bitcode in some cases, but doesn't work well for static libraries.

**Comment by ianamason** [comment]
The wllvm pip package has been fixed. So has the SRI repo of wllvm, I will push it upstream at some
stage.

I do not know much about the gold linker other than it  is used for LTO.  Our tools, wllvm and gllvm,
are really only used to produce bitcode from a build. We use other tools to play with 
the bitcode.  Like [OCCAM](https://github.com/SRI-CSL/OCCAM) for example. 

Both gllvm and wllvm are agnostic about the LLVM version and
are pretty robust. Something like the gold linker sounds a bit fragile, and hard to fix if things go wrong.
