### ISSUE TITLE
Any ways to compile kernel in -O0

### ISSUE THREAD

**Issue by chenyueqi** [SRI-CSL/gllvm#24]
Thanks a lot for providing such a useful tool. Is there anyway with the help of this tool to compile kernel in O0?

**Comment by ianamason** [comment]
If it compiles with gcc or clang it should work with gclang. If it doesn’t show me the errors and I will fix it this week.

**Comment by ianamason** [comment]
Can I close this?

**Comment by chenyueqi** [comment]
I've searched online and found Kernel cannot be compiled in O0. So, go head and close this issue. Thanks a lot.

**Comment by ianamason** [comment]
Yes I though that might be the case. You can't compile libc without optimization, so I suppose
the kernel is just as bad.
