### ISSUE TITLE
add LLVM plugin when compile kernel

### ISSUE THREAD

**Issue by chenyueqi** [SRI-CSL/gllvm#26]
Hi, is there anyway to add LLVM plugin when compiling kernel with gllvm? Thanks a lot.

**Comment by ianamason** [comment]
Unsure of what you want.  If you can do it with clang, then you can do it with gclang.
The usual workflow is to build the bitcode, then analyze it.  This also works in the case of the
kernel.

**Comment by chenyueqi** [comment]
Thanks for your response. I would like to use a LLVM plugin to add some metadata to the IR when compiling kernel. For usual program, it would be fine to do like "clang -Xclang -load -Xclang PLUGINNAME.so XXX.c". However, for the kernel, if I want to do the same thing, what should I do?

**Comment by ianamason** [comment]
Could aliasing `clang` to `clang -Xclang -load -Xclang PLUGINNAME.so` work?

**Comment by ianamason** [comment]
Or if not writing your own wrapper to clang that gclang will wrap instead of clang itself.
The bottom line is that I don't think this is glang's business to do.

**Comment by ianamason** [comment]
Can I close this @chenyueqi ?

**Comment by chenyueqi** [comment]
sure, please go ahead. Thanks a lot.
