### ISSUE TITLE
Failed to link for projects with -fopenmp

### ISSUE THREAD

**Issue by HongxuChen** [SRI-CSL/gllvm#28]
When the project is built with `openmp` support, it sometimes fails. For example, for [pxz](https://github.com/jnovy/pxz), when `export CC=gclang`, it reports

```
gclang -o pxz  -O2 -Wall -Wshadow -Wcast-align -Winline -Wextra -Wmissing-noreturn -fopenmp -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE pxz.c  -llzma -DPXZ_BUILD_DATE=\"`date +%Y%m%d`\" -DPXZ_VERSION=\"4.999.9beta\"
.pxz.o: In function `main':
pxz.c:(.text+0x3ad): undefined reference to `__kmpc_global_thread_num'
pxz.c:(.text+0x5d3): undefined reference to `omp_get_max_threads'
pxz.c:(.text+0x94a): undefined reference to `__kmpc_push_num_threads'
pxz.c:(.text+0x978): undefined reference to `__kmpc_fork_call'
.pxz.o: In function `.omp_outlined.':
pxz.c:(.text+0xec1): undefined reference to `__kmpc_for_static_init_8u'
pxz.c:(.text+0x1165): undefined reference to `__kmpc_for_static_fini'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR:clang [.pxz.o -llzma -o pxz] failed to link: exit status 1.
```

It seems that there needs to be some special treatment for `-fopenmp`.

**Comment by ianamason** [comment]
Thanks for the bug report @HongxuChen. Yes the default interpretation for a flag is that it is compile only. I have added the information that "-fopenmp" is both compile and link. So hopefully this will fix your problem. It would  be nice if this partition of flags could be easily groked from the clang code base, but I have not yet succeeded with this dream.

**Comment by HongxuChen** [comment]
Thanks, the commit fixes!
Yes, that's really hard as there are so many options undocumented.
