### ISSUE TITLE
Compiler lacks asm-goto support.

### ISSUE THREAD

**Issue by zhanggenex** [SRI-CSL/gllvm#29]
when building linux kernel 5.0.1 with wllvm(llvm-7.0.0) `make CC=wllvm HOSTCC=wllvm` , I got
**Compiler lacks asm-goto support.**
can anybody help me?

**Comment by ianamason** [comment]
Sounds familiar. I am traveling at the moment so I can’t do much. I know that you can only use certain compilers. We have a github repo dedicated to building the kernel. Take a look there. Kernel-specialization over at SRI-CSL.

**Comment by zhanggenex** [comment]
@ianamason 
You mean [https://github.com/paul-naert/kernel-specialization](url)?
I will try, thanks a lot!

**Comment by ianamason** [comment]
Yes. But SRI-CSL’s fork might be more up to date.

**Comment by ianamason** [comment]
Yes ( I have my laptop now) [this](https://github.com/SRI-CSL/kernel-specialization.git) one is where the most recent action has been, after @paul-naert finished his internship at SRI.

**Comment by zhanggenex** [comment]
@ianamason 
I will have a try, thanks!
