### ISSUE TITLE
Bitcode generation conflict when two files have the same name but different extensions

### ISSUE THREAD

**Issue by artemdinaburg** [SRI-CSL/gllvm#30]
Hi Ian,

I recently ran into an issue in a project with a C and C++ file have the same name but different extension (`.c` vs `.cpp`). The result being that the bitcode from one is clobbered by the other.

To reproduce, try the example below:

```
root@3dece5d8f0c9:/tmp/gllvm# cat test.c
#include <stdio.h>

int main(int argc, const char *argv[]) {
	printf("Hello from C!\n");
	return 0;
}
root@3dece5d8f0c9:/tmp/gllvm# cat test.cpp
#include <iostream>

int main(int argc, const char *argv[]) {
	std::cout << "Hello from C++" << std::endl;
	return 0;
}
root@3dece5d8f0c9:/tmp/gllvm# gclang -o test.c.bin test.c
objcopy: st0NVLch: Failed to find link section for section 8
objcopy: st0NVLch: Failed to find link section for section 8
root@3dece5d8f0c9:/tmp/gllvm# gclang++ -o test.cpp.bin test.cpp
objcopy: stmMWA24: Failed to find link section for section 13
objcopy: stmMWA24: Failed to find link section for section 13
root@3dece5d8f0c9:/tmp/gllvm# get-bc -b -o test.c.bc test.c.bin
Bitcode file extracted to: test.c.bc.
root@3dece5d8f0c9:/tmp/gllvm# llvm-dis test.c.bc
root@3dece5d8f0c9:/tmp/gllvm# grep 'C++' test.c.ll
@.str = private unnamed_addr constant [15 x i8] c"Hello from C++\00", align 1
root@3dece5d8f0c9:/tmp/gllvm#
```

The root cause seems to be that `getArtifactNames` strips the extension from the source file and appends `.bc`. Would it be feasibly to either keep the full file name before appending `.bc`, or use some kind of content hash to name the files?

**Comment by ianamason** [comment]
So it may succeed if you use the bitcode archive feature (the documentation is currently only in one [place](https://github.com/SRI-CSL/whole-program-llvm)), which isn't this repo.  Try that. If it doesn't work, I can fix this guy to handle this obscure case. Looks like you need to upgrade your objcopy too.

**Comment by artemdinaburg** [comment]
We weren't able to get the archive feature to work for our (admittedly unusual) use-case, but we did re-organize the source to build the .c and .cpp in different directories, which worked around the issue.

A fix would be nice, but I can understand if its not a priority since this is a fairly unusual situation.

**Comment by ianamason** [comment]
I think it is a very easy fix. Let me see if it breaks anything.

**Comment by ianamason** [comment]
Artem, See if this works for you ...

**Comment by artemdinaburg** [comment]
Confirming this fixes the issue, thanks!
