### ISSUE TITLE
extractFile() uses hardcoded "ar" executable

### ISSUE THREAD

**Issue by arrowd** [SRI-CSL/gllvm#31]
FreeBSD has pretty old `ar` in the base system, so we need to use custom `ar`. However, `extractFile()` function in `extractor.go` doesn't take in account command line or environment overrides.

**Comment by ianamason** [comment]
Thanks @arrowd, I will fix this today.

**Comment by ianamason** [comment]
@arrowd, so I added a switch 
```
Usage of get-bc:
  -a string
    	the llvm archiver (i.e. llvm-ar)
  -b	build a bitcode module
  -l string
    	the llvm linker (i.e. llvm-link)
  -m	write the manifest
  -n int
    	maximum llvm-link command line size (in bytes)
  -o string
    	the output file
  -r string
    	the system archiver (i.e. ar)
  -s	sort the bitcode files
  -t	keep temporary linking folder
  -v	verbose mode
```

You want the new `-r` switch.  I haven't tested it yet. Let me know if its totally broken.

**Comment by arrowd** [comment]
That did helped a bit. It now uses correct `ar` executable, but fails down road with

```
DEBUG:defaultPath = llvm-ar
DEBUG:envPath = 
DEBUG:usrPath = llvm-ar90
DEBUG:path = llvm-ar90
DEBUG:defaultPath = llvm-link
DEBUG:envPath = 
DEBUG:usrPath = llvm-link90
DEBUG:path = llvm-link90
INFO:ea.Verbose: false
INFO:ea.WriteManifest: false
INFO:ea.BuildBitcodeModule: false
INFO:ea.LlvmArchiverName: llvm-ar90
INFO:ea.LinkerName: llvm-link90
INFO:ea.OutputFile: 
INFO:ea.InputFile: a.out
INFO:ea.InputFile real path: a.out
INFO:ea.LinkArgSize 0
INFO:ea.KeepTemp false
WARNING:Error reading the .llvm_bc section of ELF file a.out.
INFO:handleExecutable: artifactPaths = []
INFO:Calling [get-bc -a llvm-ar90 -l llvm-link90 -r llvm-ar90 a.out] DID NOT TELL US WHAT HAPPENED
```

**Comment by ianamason** [comment]
So I need to know a bit more about `a.out` to debug this. How was it generated?  When I mimic your line with say 
```
get-bc -a llvm-ar -l llvm-link -r llvm-ar -o node.bc ./node-v10.16.0/node
```

after building nodejs (I just added that as a stress test example) I get my node.bc file just fiine.

**Comment by ianamason** [comment]
P.S. I am going offline for an hour...

**Comment by arrowd** [comment]
Ok, this is super strange, but I did chased it down.

FreeBSD's `objcopy` is elftooclhain one. Running `objcopy --add-section .llvm_bc=.test.c.o.bc .test.c.o` first time it does nothing. However, running the same command again actually adds the section! It's clearly a bug on our side, and I'll report it upstream.

For now, would it be possible to add another override to `objcopy` executable being used?

**Comment by ianamason** [comment]
Sure, that's on the compile side, so it will have to be (another) environment variable. Shouldn't take long.

**Comment by ianamason** [comment]
bce21265af1403d78adbb53cf16bfc7378b4afb0 has the update. You're my tester @arrowd

**Comment by arrowd** [comment]
Yay, it works! Thanks for fixing this.

Now, the last thing I'd ask is to make a new release, so that we can update our package: https://www.freshports.org/devel/gllvm

**Comment by ianamason** [comment]
Sure. When I get back from lunch.

**Comment by ianamason** [comment]
[v1.2.5](https://github.com/SRI-CSL/gllvm/releases/tag/v1.2.5) is live.

**Comment by arrowd** [comment]
Great, thanks for your prompt support.
