### ISSUE TITLE
Is that possible for 'get-bc' to handle multiple definiton ？

### ISSUE THREAD

**Issue by zyscoder** [SRI-CSL/gllvm#33]
Hello, 
I tried to use gllvm to generate a whole llvm bitcode for a project. For some reasons, the objects I linked together suffered the problem of multiple definiton, and I used '-Wl, --allow-multiple-definition' to link them together successfully. 
The same problem happened when I tried to use 'get-bc' to generate the whole llvm bitcode. Is that possible to give any ldflag like '--allow-multiple-definition' to llvm-link, so that it can handle this problem ? And how can I give this ldflag from get-bc to llvm-link ?
I noticed that llvm-link supports the flag '--override=file'. I feel it may be helpful to solve my problem.  Is that possible to transfer this flag from get-bc to llvm-link? Or may I get the command lines ‘get-bc’ is going to run (like '--just-print' for 'make') ?
Thanks.

**Comment by zyscoder** [comment]
I noticed that llvm-link supports the flag '--override=file'. I feel it may be helpful to solve my problem.  Is that possible to transfer this flag from get-bc to llvm-link? Or may I get the command lines ‘get-bc’ is going to run (like '--just-print' for 'make') ?

**Comment by ianamason** [comment]
Oh I forgot to mention that you can use the -m flag to get-bc to get a list of all the bitcode
files, and go from there, linking however you want.

**Comment by zyscoder** [comment]
Thank you very much. I'm trying to read your code of gllvm and have noticed the -m flag. I'm going to try it. Thank you again.

**Comment by ianamason** [comment]
I am going to close this issue. If you need more help, just reopen it, but perhaps with more details? Like the package you are trying to build?
