### ISSUE TITLE
Error When Compiling Linux Kernel

### ISSUE THREAD

**Issue by michael-hahn** [SRI-CSL/gllvm#36]
Hi there,

Thanks for building this amazing cool!

I am interested in using `gllvm` to build the Linux kernel and get LLVM bitcode to perform some out-of-tree analysis.
I am trying to build a stable version of the kernel (v5.6.7) with LLVM/Clang 10. To start small, I tried with minimal kernel configuration: `make tinyconfig` and used `make menuconfig` to enable 64-bit build (following the instructions [here](https://github.com/SRI-CSL/gllvm/tree/master/examples/linux-kernel) but with a newer kernel version). I first noticed:
```
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
objcopy: scripts/kconfig/stXGmaKH: Failed to find link section for section 13
objcopy: scripts/kconfig/stXGmaKH: Failed to find link section for section 13
  HOSTCC  scripts/kconfig/confdata.o
objcopy: scripts/kconfig/stnJgedW: Failed to find link section for section 13
objcopy: scripts/kconfig/stnJgedW: Failed to find link section for section 13
  HOSTCC  scripts/kconfig/expr.o
objcopy: scripts/kconfig/stm5a8r4: Failed to find link section for section 11
objcopy: scripts/kconfig/stm5a8r4: Failed to find link section for section 11
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
objcopy: scripts/kconfig/stfkgSo4: Failed to find link section for section 12
objcopy: scripts/kconfig/stfkgSo4: Failed to find link section for section 12
  HOSTCC  scripts/kconfig/preprocess.o
objcopy: scripts/kconfig/stkroaSV: Failed to find link section for section 13
objcopy: scripts/kconfig/stkroaSV: Failed to find link section for section 13
  HOSTCC  scripts/kconfig/symbol.o
objcopy: scripts/kconfig/stuMzhHr: Failed to find link section for section 14
objcopy: scripts/kconfig/stuMzhHr: Failed to find link section for section 14
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
...
```
`objcopy` seems to have trouble find link section for many files.
I also tried to build an earlier version (v4.14.39) of the kernel as in [this example](https://github.com/SRI-CSL/gllvm/tree/master/examples/linux-kernel), but received similar issue.
 
My environment:
```
GNU objcopy (GNU Binutils for Ubuntu) 2.30 
```
Output from `gsanity-check`:
```
Happily sitting atop "linux" operating system.

The C compiler clang-10 is:

	clang version 10.0.0-++20200412073436+50d7e5d5e7d-1~exp1~20200412054917.132

The CXX compiler clang++-10 is:

	clang version 10.0.0-++20200412073436+50d7e5d5e7d-1~exp1~20200412054917.132

The bitcode linker llvm-link-10 is:

	LLVM version 10.0.0

The bitcode archiver llvm-ar-10 is:

	LLVM version 10.0.0
```
I also archived bitcode.

Thank you for your help.

**Comment by ianamason** [comment]
I think that `objcopy` is your problem @michael-hahn .  It has a recent history of not being totally reliable. Especially since, `clang` has not been shy in creating new segments for various `llvm` related things.

I filed one bug against them a while ago, which I think they fixed. But I haven't been active
in this area lately.  I suggest you start by looking at the `objcopy` as the culprit, and try and build one from the latest source. Feel free to keep this issue open, and post your findings, it will help people who follow on in your footsteps.

**Comment by michael-hahn** [comment]
Thank you @ianamason for your reply!
I just compiled the latest `binutils` from source and ran `gllvm` using `objcopy` v2.34, and I no longer saw those printouts -- so it seems like they have indeed fixed the issue you filed! However, now I see this warning:
```
...
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.o
WARNING: vmlinux.o (.llvm_bc): unexpected non-allocatable section.
Did you forget to use "ax"/"aw" in a .S file?
Note that for example <linux/init.h> contains
section definitions for use in .S files.

  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      vmlinux
...
```
Do you happen to know what it is? 
Thank you very much!

**Comment by ianamason** [comment]
That looks to be like something complaining about the section we inject into the object file.
You will have to dig a bit deeper into what is doing the complaining, and whether it is actually an
error or just a warning.
