### ISSUE TITLE
Supporting builds that don't generate intermediate objects

### ISSUE THREAD

**Issue by woodruffw** [SRI-CSL/gllvm#42]
Some (misdesigned) builds don't do the standard `[.c] -> [.o] -> exe` pattern, but instead invoke the compiler just once, passing all of the `.c` files directly to the frontend and asking it to emit the fully linked executable.

Expressed as a Make rule:

```make
$(PROG): $(SOURCES)
	$(CC) $(SOURCES) -o $@.bin $(CFLAGS)
```

GLLVM currently fails to embed bitcode for these builds, since it tries to find a corresponding `.o` for each source in `$(SOURCES)` to call `objcopy` with. Those `.o` files don't exist, so the `objcopy` fails with a missing file error. 

My Go skills aren't great, but I *think* the fix is going to be somewhere in `getArtifactNames`: https://github.com/SRI-CSL/gllvm/blob/9cd27f7da814250906312a83fcead6e42a3ed076/shared/parser.go#L465-L484

If I understand that function correctly, it needs to return the name of the executable specified to the compiler rather than trying for the presence of a `.o` file. But I'm also not sure how that'll interact with `objcopy`, since `--add-section`'s append/overwrite behavior isn't well documented (and we'll end up calling it multiple times on the same file).

**Comment by woodruffw** [comment]
Looked a little more closely at this, and I'm now stumped as to why this isn't working as-is. Per `buildAndAttachBitcode`, we _should_ be compiling each of the individual `.o` files:

https://github.com/SRI-CSL/gllvm/blob/beca29f43d356bc7b858fc9ff2c7af82384269e4/shared/compiler.go#L108-L133

Specifically, we should always hit the `else` branch and then the `hidden` branch, since we're not running in compile-only (i.e., `-c`) mode. However, it seems like the invocations in `buildObjectFile` never produce any object files and never fail either (since nothing shows up in the debug logs). I'll keep digging.

**Comment by ianamason** [comment]
This used to work.  We split the "compile + link" into two steps. I may have time to look at it, but I am surprised that 
it doesn't work out of the box.

**Comment by woodruffw** [comment]
> but I am surprised that it doesn't work out of the box.

Yeah, me too. I did a bit more digging, and I'm surprised to see `IsCompileOnly: true` in the parser results:

```
DEBUG:Compile using parsed arguments:
InputList:         [redacted.c mongoose.c db_plugin_sqlite.c -o redacted.bin -g -W -Wall -Werror -I../.. -lcrypt -ldl -fno-stack-protector -lsqlite3]
InputFiles:        [redacted.c mongoose.c db_plugin_sqlite.c]
ObjectFiles:       []
OutputFilename:    redacted.bin
CompileArgs:       [-g -Wall -Werror -I../.. -fno-stack-protector]
LinkArgs:          [-lcrypt -ldl -lsqlite3]
ForbiddenFlags:    []
IsVerbose:         false
IsDependencyOnly:  false
IsPreprocessOnly:  false
IsAssembleOnly:    false
IsAssembly:        false
IsCompileOnly:     true
IsEmitLLVM:        false
IsLTO:             false
IsPrintOnly:       false
```

So that explains why the `buildObjectFile` calls aren't made, but I'm not sure *why* `isCompileOnly` is being set. Will keep looking...

**Comment by woodruffw** [comment]
Okay, it's definitely the `-W` matcher in `argsExactMatches`. When I remove that, the build completes successfully and I can use `get-bc` to extract the bitcode from the compiled product.

**Comment by ianamason** [comment]
That indeed looks dodgey. Seems lik ethey should both be `compileUnaryCallback`s no?

**Comment by woodruffw** [comment]
> That indeed looks dodgey. Seems like they should both be `compileUnaryCallback`s no?

Yep! I'm testing that now, will open a PR in a moment if it works.

**Comment by woodruffw** [comment]
Opened #43.
