### ISSUE TITLE
Broken install with go 1.16:  github.com/SRI-CSL/gllvm/cmd/gclang++: malformed import path "github.com/SRI-CSL/gllvm/cmd/gclang++": invalid char '+'

### ISSUE THREAD

**Issue by qtcdxxyuc** [SRI-CSL/gllvm#44]
malformed import path "gllvm/cmd/gclang++": invalid char '+'
go get gclang and other is succeed.

**Comment by ianamason** [comment]
I think the way I install it is described in the [README.md](https://github.com/SRI-CSL/gllvm/blob/master/README.md)
```
go get github.com/SRI-CSL/gllvm/cmd/...
```
Which works fine for me.

**Comment by ianamason** [comment]
Maybe this is a real problem, will have to look into it.

**Comment by ianamason** [comment]
This appears to be a problem cause by the latest go. 
```
go 1.15.8 -> 1.16
```

I can now reproduce it:

```
CSL-CAS7352:STITCHES_Inputs e27658$ go get github.com/SRI-CSL/gllvm/cmd/...
go: downloading github.com/SRI-CSL/gllvm v1.3.0
github.com/SRI-CSL/gllvm/cmd/gclang++: malformed import path "github.com/SRI-CSL/gllvm/cmd/gclang++": invalid char '+'
CSL-CAS7352:STITCHES_Inputs e27658$
```

**Comment by ianamason** [comment]
OK so the new go module system appears to have a draconian view of what things can be named.
It does not allow executables to be called things like `g++` or `gclang++` or `clang++`.  Seems
a bit monocultural to me. Anyway I have filed an [issue](https://github.com/golang/go/issues/44776) but I am not holding my breath. We shall see.

In the meantime the work around appear to be:

```
GO111MODULE=off go get github.com/SRI-CSL/gllvm/cmd/...
```

If all else fails, there might be a rename in gllvm's future.

**Comment by ianamason** [comment]
Think this saga is over. Though at some stage I need to update the README.
