### ISSUE TITLE
Why be different?

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/gllvm#5]
I'm not sure why we do not just produce a drop in replacement for  wllvm.
Having different environment variables seems logical at first, but then when
you start using it, debugging it etc, it just seems a bit silly. 

Strong opinions?

**Comment by loicgelle** [comment]
@ianamason Mere consistency between the name of environment variables and the name of the project. Also producing drop in replacements can lead to imitating legacy code instead of cleaning and rethinking it.

**Comment by ianamason** [comment]
Not really convincing. I think we should accept either form to make use easier. Being pedantic doesn't help the users much.

**Comment by loicgelle** [comment]
On the other side, putting up with legacy names and behavior doesn't help anyone. Things that are not logical are never good for long-term maintenance.

Now that you have read my strong opinion and considered it as being pedantic, you are free to go for your solution.

**Comment by ianamason** [comment]
I do not believe that logic requires a "G" in the environment variable string rather than a "W".
Nor do I think we are going to regret it one way or the other down the track.
So you cannot bully me with that routine. But there are other issues that are more important.

**Comment by loicgelle** [comment]
I am not bullying you with anything. I am just pointing out that opening an issue for that is useless since you have stronger opinions than anyone. As for me, you can close it.

**Comment by ianamason** [comment]
actually I was hoping for a "thats a good idea, lets not reinvent the wheel, and it might
encourage wllvm users to try out gllvm, if all they have to do is go get it." but oh well.

**Comment by ianamason** [comment]
OK so I decided it was much better to be a drop in replacement for wllvm (and to be able
to quickly compare one with the other), so I would like to make the environment variables
match (i.e. use the exact same environment variables). To this end I have isolated all the
interactions with the environment into one place (environment.go) and so I would like these to be updated to match wllvm. I will let @loicgelle  do this so that he can keep his system working smoothly. There may be some futzing needed in the travis stuff, too.

**Comment by loicgelle** [comment]
@ianamason I will not have the time to do it before Friday. If you want to do it, either keep the GLLVM* variables working for now or ping me when you push your changes so that I can adapt the system.

**Comment by ianamason** [comment]
As I said in the email reply, Friday is fine.  The desired variables are commented out, so not
much labor is required. Thanks.

**Comment by loicgelle** [comment]
Changes have been made. Thanks.
