### ISSUE TITLE
Deduplicating paths when merging bitcode?

### ISSUE THREAD

**Issue by woodruffw** [SRI-CSL/gllvm#53]
I'm trying to use GLLVM to instrument a couple of pathological build systems, and I've run into a case where the `Extractor` is apparently discovering multiple references to the same bitcode stored within an executable:

```
INFO:handleExecutable: artifactPaths = [
    /a/long/path/.foo.c.o.bc
    /a/long/path/.foo.c.o.bc
]
```

This in turn causes `llvm-link` to fail, since attempting to merge two copies of the same bitcode together (trivially) causes symbol clashes.

I suspect that the underlying problem is somewhere deeper in this build system's (ab)use of the standard build tools, but I think a reasonable workaround here is to ensure that the process of resolving `artifactPaths` into `filesToLink` deduplicates any identical paths.

Does that sound reasonable? If so, I can create a quick PR for your consideration 🙂

**Comment by ianamason** [comment]
Yes it seems reasonable. But what would I know? We can merge it and see if the world sinks.

**Comment by woodruffw** [comment]
Update on this: #54 seems to work well for our purposes! We'll keep testing and I'll report back.
