### ISSUE TITLE
Log files for warnings/TU's no bitcode was emitted

### ISSUE THREAD

**Issue by adriaanjacobs** [SRI-CSL/gllvm#57]
Hi, if this is not already implemented and is something you/the community is interested in, I can add it in over the weekend myself and create a quick pull request.

During compilation, warnings sometimes get emitted about generating no bitcode for some files (from what I've seen, mostly/only assembly source files). It would be cool if info about this (or maybe about gllvm warnings in general) could be optionally redirected to some log file, so that it could be examined later on to deal with these external modules for IR modules manually.

Simply examining stdout/stderr is a bit tedious, since it is often interlaced with other compiler warnings (unrelated to the additional operation of gllvm) and when using parallelized builds, warnings appear in a mixed, non-deterministic ordering. Writing to this logfile should therefore perhaps globally synchronize across all currently running gllvm instances.

A more ad-hoc fix would be to include the filename of the TU for which no bitcode was emitted in the warning :), maybe this doesn't have to be something universally applicable.

Is this something that you think would be useful? As I said, I can create a patch over the weekend if so. :)

**Comment by ianamason** [comment]
Did you see the part in the README about:
```
export WLLVM_OUTPUT_FILE=/tmp/gllvm.log
```

**Comment by adriaanjacobs** [comment]
Ah excuse me, I somehow missed that. Thank you
