### ISSUE TITLE
gclang does not recognize clang flags

### ISSUE THREAD

**Issue by peterbaile** [SRI-CSL/gllvm#63]
Hi,

As seen in the screenshot below, when `gclang` is compiling the c files, it seems that it doesn't recognize a lot of the flags that clang understands. The flags `-target`, `-mcpu`, etc are valid as per the [clang docs](https://releases.llvm.org/11.0.0/tools/clang/docs/CrossCompilation.html#cpu-fpu-abi). I'm wondering why this is the case.

<img width="1278" alt="Screen Shot 2022-04-13 at 9 33 11 AM" src="https://user-images.githubusercontent.com/42967671/163192185-68abc797-1d76-4905-a94b-63484bb5ce3d.png">

Thanks!

**Comment by peterbaile** [comment]
got it, thanks! so should I be modifying [this function](https://github.com/SRI-CSL/gllvm/blob/master/shared/parser.go#L159)?

**Comment by ianamason** [comment]
Exactly.  It's a flaw that wllvm and gclang share, but I do not see any feasible way around it.
I once looked at the clang code for doing this, but gave up the idea of using that.

**Comment by peterbaile** [comment]
If I download the code and make some local changes, how would I build the code to get the binaries: `gclang` etc? Thanks!

**Comment by ianamason** [comment]
So when you install gllvm  golang sucks down the repo and builds it locally.
So you should already have a copy of the repo beneath your GOPATH.
I can never remember the rest, which is why you will see this [file](https://github.com/SRI-CSL/gllvm/blob/master/ians-notes.txt), and the incantation:
```
go install github.com/SRI-CSL/gllvm/cmd/...
```
I think you do it in the local copy of the repo.

**Comment by ianamason** [comment]
Oh I forgot, there is also a makefile to remind me why I entered the room.
```
make
```
in the repo will list the targets. Happy hacking.
