### ISSUE TITLE
gflang has .mod file conflict issue.

### ISSUE THREAD

**Issue by clarence-glx** [SRI-CSL/gllvm#64]
output log:
F90-F-0004-Corrupt or Old Module file ./globalv.mod (fortran.f90: 16)
F90/aarch64 Linux Flang - 1.5 2017-05-01: compilation aborted
ERROR:Failed to build bitcode file for fortran.f90 because: exit status 1
objcopy: st1PvZpd: Failed to find link section for section 17
objcopy: st1PvZpd: Failed to find link section for section 17

shared/compiler.go
`
wg.Add(2)
go execCompile(compilerExecName, pr, &wg, &ok)
go buildAndAttachBitcode(compilerExecName, pr, &bcObjLinks, &newObjectFiles, &wg)
wg.Wait()
`

when a fortran source file has module,  both _go execCompile_ and go _buildAndAttachBitcode_ will try to generate .mod file that has the same name which become a conflict.
here is the patch
`		
if compiler == "flang" {
			wg.Add(1)
			go execCompile(compilerExecName, pr, &wg, &ok)
			wg.Wait()
			wg.Add(1)
			go buildAndAttachBitcode(compilerExecName, pr, &bcObjLinks, &newObjectFiles, &wg)
			wg.Wait()
		} else {
			wg.Add(2)
			go execCompile(compilerExecName, pr, &wg, &ok)
			go buildAndAttachBitcode(compilerExecName, pr, &bcObjLinks, &newObjectFiles, &wg)
			wg.Wait()
		}
`

**Comment by ianamason** [comment]
Thanks. Could you actually do a (tested) pull request? I have never used flang.

**Comment by clarence-glx** [comment]
https://github.com/SRI-CSL/gllvm/pull/65
It has been tested in my project and works fine.
