### ISSUE TITLE
how to add debug info when compile kernel with gllvm?

### ISSUE THREAD

**Issue by wliuxingxiangyu** [SRI-CSL/gllvm#67]
@ianamason 
Hi, thanks for the nice tool!

I add -g to the CFLAGS to generate debug info when compile kernel with gllvm. But the llvm IR do not show the source code line number.
`$ make CC=gclang CFLAGS+="-g" -j$(nproc --all)`

Could you please give some suggestions to show the source code line number in the generated llvm IR?  
Any suggestions will be appreciated.

**Comment by ianamason** [comment]
This has nothing to do with gllvm.  You should look to see how to make clang do what you want.
We just wrap the compiler, it does all the work.

**Comment by ianamason** [comment]
Google tells [me](https://stackoverflow.com/questions/38319288/how-to-get-source-line-number-from-ll-file-llvm) that you use both `-O0` and `-g`.

**Comment by wliuxingxiangyu** [comment]
@ianamason 
thank you for your suggestions.
I make it with the config option.
CONFIG_DEBUG_INFO=y
