### ISSUE TITLE
Cannot relink proper binaries when they include assembly or complex linking invocations

### ISSUE THREAD

**Issue by loicgelle** [SRI-CSL/gllvm#8]
@ianamason The fact that we forget about the build invocations is a problem. Usual workflow would be:

- I build a binary using gllvm
- I extract the bitcode from it using get-bc
- I make transformations on the bitcode (making optimization, specialization, adding logging...)
- I want to rebuild a binary out of it and... it fails because we don't keep track of the build invocations (in particular of fun like --start-group ... --end-group) and we did not store object files that don't have bitcode for it (because they were built from assembly)

It would be nice to store either assembly or compiled assembly in the store, along with the bitcode files, and also to keep track of build invocations into a more complex manifest file that could be read by a third tool, `gllvm-relink` that would rebuild the binaries.

What do you think about that?

**Comment by ianamason** [comment]
I have discussed this with @HassenSaidiatSRI on several occasions.
I think it is something we should do. I think we should be careful to 
capture as many of the use cases as we can.  I think there are examples
where the assembly is built on the fly, so we should design this with an
open mind. I think gmp is one such example. You no doubt will com across
more in your project.

**Comment by ianamason** [comment]
Do we want two sections or just one?

**Comment by loicgelle** [comment]
A lot of invocations make use of things like linking groups. One solution would be to store a manifest in the bc store directory for each binary, that would keep track of the exact build invocation. `get-bc` could then extract the bitcode from the binary, and maybe generate a Makefile that can be used to relink.

**Comment by loicgelle** [comment]
In the ELF files you mean? I have no opinion about this. Maybe an external file stored into the store can do the trick.

**Comment by ianamason** [comment]
so the store would become compulsory?
maybe keep it as simple as possible until forced to do otherwise.

**Comment by loicgelle** [comment]
Do you think that storing the exact linking command into an elf section would be okay? Some invocations are very long

**Comment by ianamason** [comment]
Lets keep it out of the elf or mach-o until we know exactly what we are doing. 
Earlier versions of wllvm
actually stored the bitcode in the elf, but I am not sure why they moved to just paths, apart from
the obvious simplicity @travitch?

**Comment by loicgelle** [comment]
@ianamason Think about static binaries like clang that are 80M stripped... I think that linking or something would fail if you were to include the bitcode directly into the elf.

**Comment by ianamason** [comment]
Not to mention having to parse the section and separate out the modules for llvm-linking

**Comment by loicgelle** [comment]
Actually is it useful to NOT use the store @ianamason ?

**Comment by ianamason** [comment]
So it sounds premature to settle on a where, when we don't seem to have settled on a what.
we have assembly, linking commands, what else?

**Comment by loicgelle** [comment]
Well I think it is enough. Each time you are building a binary, you check every source into the linking command: either it is an object file for which you have bitcode, or it is an object file that you have to store. Then you can keep track of the linking command.

**Comment by ianamason** [comment]
I am confused. Are we going to keep the assembly, or just the object file it generates?
Better for analysis to have the former rather than the latter. Still Rome wasn't built in a day.

**Comment by loicgelle** [comment]
I was thinking about the object because then you only have to re-link to get an executable back. If you store the assembly, then you also have to store its building invocation (although I agree it should be straightforward). Actually I don't really have a strong opinion about that.

**Comment by travitch** [comment]
`wllvm` used to store bitcode in ELF sections (which I did prefer), but it ran into trouble with some very large binaries.  The size of the bitcode (with debug information) exceeded the maximum size of ELF sections, which broke everything.  After finding that, I switched over to just storing paths in the ELF section.

**Comment by ianamason** [comment]
one day. perhaps.
